### PR TITLE
Post field name conflict and DB API update

### PR DESCRIPTION
**Pull request by grimmdude**
Renamed `type` to `reminder_type` and made necessary changes to database API usage per https://trac.edgewall.org/wiki/TracDev/DatabaseApi#Trac1.0API.

References issue #8 

-Garrett

### CODE REVIEW

**Comment by rjollos** [comment]
Looks good. I made some suggestions - mostly style and compatibility changes. Thanks!

**Comment by grimmdude** [comment]
Thanks @rjollos, though I'm not seeing the suggestions?

**Comment by rjollos** [comment]
I didn't realize I needed to "submit changes" for the entire review. Suggestions should be displayed in this ticket and the PR now.

**Comment by grimmdude** [comment]
Hi @rjollos,

I've made changes per your suggestions, thanks.  Python isn't my first language so happy to learn.  Regarding squashing commits, I've never done that and was having some trouble with it.

-Garrett

**Comment by rjollos** [comment]
@grimmdude Thanks, I'll review again and squash changes before merge.

**Comment by grimmdude** [comment]
Hi @rjollos,

Just checking on this one, thx

-Garrett

**Comment by rjollos** [comment]
Sorry for delay. Haven't forgotten. I'll aim to get it merged by tomorrow.

**Comment by rjollos** [comment]
Merged a4f1fd4669289f20083b54021f89e8d127c43672 and a8b116bcac0d3eb48552af11115f880d6ed4c69b. Let me know if you spot any issues.

**Pull request closed without merging**
